### ISSUE TITLE
RuntimeError: CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by kawaiiGTR** [sovit-123/vision_transformers#21]
Trying to run DETR on custom dataset. When executing the launch command:

- python tools/train_detector.py --epochs 20 --batch 2 --data data/aquarium.yaml --model detr_resnet50 --name detr_resnet50

The output is:
### RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
-----------
After some digging the error either points to class mismatch or problematic activation function. Either way it doesn't seem to work!! :(

Any advise on how to get this working? Cheers!

**Comment by sovit-123** [comment]
Hello @kawaiiGTR Can you please let me know how many classes you have and if you can provide the your custom dataset YAML file information here?

**Comment by kawaiiGTR** [comment]
Hi, thanks for your reply! I have 115 classes + 1 (as stated in the script).
[aquarium_yaml.txt](https://github.com/sovit-123/vision_transformers/files/15497174/aquarium_yaml.txt)

**Comment by kawaiiGTR** [comment]
I attach a more detailed console log: 
/opt/conda/conda-bld/pytorch_1712608847532/work/aten/src/ATen/native/cuda/NLLLoss2d.cu:106: nll_loss2d_forward_kernel: block: [0,0,0], thread: [3,0,0] Assertion `t >= 0 && t < n_classes` failed.
Traceback (most recent call last):
  File "/media/niko/Xtra/Work/DETR/vision_transformers/tools/train_detector.py", line 327, in <module>
    main(args)
  File "/media/niko/Xtra/Work/DETR/vision_transformers/tools/train_detector.py", line 287, in main
    train_loss = train(
                 ^^^^^^
  File "/media/niko/Xtra/Work/DETR/vision_transformers/tools/utils/detection/detr/engine.py", line 37, in train
    loss_dict = criterion(outputs, targets)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/niko/anaconda3/envs/detr/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/niko/anaconda3/envs/detr/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/niko/Xtra/Work/DETR/vision_transformers/tools/utils/detection/detr/detr.py", line 237, in forward
    losses.update(self.get_loss(loss, outputs, targets, indices, num_boxes))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/niko/Xtra/Work/DETR/vision_transformers/tools/utils/detection/detr/detr.py", line 213, in get_loss
    return loss_map[loss](outputs, targets, indices, num_boxes, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/niko/Xtra/Work/DETR/vision_transformers/tools/utils/detection/detr/detr.py", line 150, in loss_boxes
    src_boxes = outputs['pred_boxes'][idx]
                ~~~~~~~~~~~~~~~~~~~~~^^^^^
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by kawaiiGTR** [comment]
=================================================================================================================================================
Layer (type (var_name))                                                Input Shape               Output Shape              Param #
=================================================================================================================================================
DETRModel (DETRModel)                                                  [2, 3, 640, 640]          [2, 100, 4]               --
├─DETR (model)                                                         [2, 3, 640, 640]          [2, 100, 4]               25,600
│    └─Joiner (backbone)                                               [2, 3, 640, 640]          [2, 2048, 20, 20]         --
│    │    └─Backbone (0)                                               [2, 3, 640, 640]          [2, 2048, 20, 20]         23,454,912
│    │    └─PositionEmbeddingSine (1)                                  [2, 2048, 20, 20]         [2, 256, 20, 20]          --
│    └─Conv2d (input_proj)                                             [2, 2048, 20, 20]         [2, 256, 20, 20]          524,544
│    └─Transformer (transformer)                                       [2, 256, 20, 20]          [6, 2, 100, 256]          --
│    │    └─TransformerEncoder (encoder)                               [400, 2, 256]             [400, 2, 256]             7,890,432
│    │    └─TransformerDecoder (decoder)                               [100, 2, 256]             [6, 100, 2, 256]          9,473,024
│    └─Linear (class_embed)                                            [6, 2, 100, 256]          [6, 2, 100, 92]           23,644
│    └─MLP (bbox_embed)                                                [6, 2, 100, 256]          [6, 2, 100, 4]            --
│    │    └─ModuleList (layers)                                        --                        --                        132,612
├─Linear (out)                                                         [2, 100, 92]              [2, 100, 114]             10,602
=================================================================================================================================================
Total params: 41,535,370
Trainable params: 41,312,970
Non-trainable params: 222,400
Total mult-adds (Units.GIGABYTES): 70.31
=================================================================================================================================================
Input size (MB): 9.83
Forward/backward pass size (MB): 1599.77
Params size (MB): 147.09
Estimated Total Size (MB): 1756.69
=================================================================================================================================================

**Comment by kawaiiGTR** [comment]
I think there is a mismatch in Linear out between Input shape [2,100,92] and the output shape [2.100,114]

**Comment by sovit-123** [comment]
Were you able to solve it?

**Comment by kawaiiGTR** [comment]
I don't know where e.g. what file I need to edit to change the size of the input layer to match the output layer. Could you kindly advise? I have 114 classes not 92.. Cheers!

**Comment by sovit-123** [comment]
Is it possible for you to provide me link to the dataset? I will be able to debug it if I have the dataset.
